#!/usr/bin/env bash

# Dotfiles setup - use after cloning dotfiles repo to .dotfiles

# dotfiles="$HOME/.dotfiles"
dotfiles=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

for i in config vim gitconfig gitignore_global bash_profile bashrc; do
  ln -s -f "$dotfiles/$i" "$HOME/.$i"
done
