#!/usr/bin/env bash

# Dotfiles setup - use after cloning dotfiles repo to .dotfiles

# dotfiles="$HOME/.dotfiles"
dotfiles=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

for i in ssh vim gitconfig gitignore_global bash_profile bashrc gdbinit; do
  ln -s -f "$dotfiles/$i" "$HOME/.$i"
done

for i in "$dotfiles"/config/*; do
  [[ -e "$i" ]] || break
  echo "$i"
  ln -s -f "$i" "$HOME/.config/$(basename "$i")"
done

cd "$dotfiles" || exit
git submodule update --init --recursive
